package com.example.restapi.msp.autenticacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11.redhat-3
 * 2016-03-17T14:50:56.455-05:00
 * Generated source version: 2.7.11.redhat-3
 *
 */
@WebService(targetNamespace = "http://bsg.gob.ec/AccesoBSGService", name = "BSG04_Acceder_BSG")
@XmlSeeAlso({com.example.restapi.wsdl.generated.ObjectFactory.class})
public interface BSG04AccederBSG {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "ValidarPermiso", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.senescyt.snna.ws.bsg.msp.autenticacion.ValidarPermiso")
    @WebMethod(operationName = "ValidarPermiso")
    @ResponseWrapper(localName = "ValidarPermisoResponse", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "ec.gob.senescyt.snna.ws.bsg.msp.autenticacion.ValidarPermisoResponse")
    public com.example.restapi.msp.autenticacion.ValidarPermisoRespuesta validarPermiso(
        @WebParam(name = "ValidarPermisoPeticion", targetNamespace = "")
        com.example.restapi.msp.autenticacion.ValidarPermisoPeticion validarPermisoPeticion
    );
}
