spring.application.name=restapi
server.port=8080
server.address=0.0.0.0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=mail.fomentoacademico.gob.ec
spring.mail.port=587
spring.mail.username=pusak.notificaciones@fomentoacademico.gob.ec
spring.mail.password=Pusak123!!!
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.ssl.trust=*

servicio.rc.url=https://interoperabilidad.dinardap.gob.ec/interoperador?wsdl
servicio.rc.usuario=InOlbSnCyT
servicio.rc.clave=<HB.762oJ!

app.frontend.activacion.url=https://pusakregistro.fomentoacademico.gob.ec/activate



# ============================================================
# renes-munoz - Registro Controlado - JTA / Atomikos
# ============================================================

spring.jta.enabled=true

# Usuarios
spring.jta.atomikos.datasource.usuarios.unique-resource-name=usuariosXA
spring.jta.atomikos.datasource.usuarios.xa-data-source-class-name=org.postgresql.xa.PGXADataSource

spring.jta.atomikos.datasource.usuarios.xa-properties.serverName=10.181.1.113
spring.jta.atomikos.datasource.usuarios.xa-properties.portNumber=5432
spring.jta.atomikos.datasource.usuarios.xa-properties.databaseName=usuarios
spring.jta.atomikos.datasource.usuarios.xa-properties.user=pusak
spring.jta.atomikos.datasource.usuarios.xa-properties.password=3U#oGib2

# Becas
spring.jta.atomikos.datasource.becas.unique-resource-name=becasXA
spring.jta.atomikos.datasource.becas.xa-data-source-class-name=org.postgresql.xa.PGXADataSource

spring.jta.atomikos.datasource.becas.xa-properties.serverName=10.181.1.113
spring.jta.atomikos.datasource.becas.xa-properties.portNumber=5432
spring.jta.atomikos.datasource.becas.xa-properties.databaseName=becas
spring.jta.atomikos.datasource.usuarios.xa-properties.user=pusak
spring.jta.atomikos.datasource.usuarios.xa-properties.password=3U#oGib2