package com.example.restapi.bsg.rc.autenticacion;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-07-09T13:52:25.386-05:00
 * Generated source version: 3.1.4
 *
 */
@WebServiceClient(name = "AccesoBSGService",
                  wsdlLocation = "https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl",
                  targetNamespace = "http://bsg.gob.ec/AccesoBSGService")
public class AccesoBSGService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://bsg.gob.ec/AccesoBSGService", "AccesoBSGService");
    public final static QName BSG04AccederBSGPort = new QName("http://bsg.gob.ec/AccesoBSGService", "BSG04_Acceder_BSGPort");
    static {
        URL url = null;
        try {
            url = new URL("https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AccesoBSGService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://www.bsg.gob.ec/sw/STI/BSGSW08_Acceder_BSG?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AccesoBSGService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AccesoBSGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccesoBSGService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AccesoBSGService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AccesoBSGService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AccesoBSGService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BSG04AccederBSG
     */
    @WebEndpoint(name = "BSG04_Acceder_BSGPort")
    public BSG04AccederBSG getBSG04AccederBSGPort() {
        return super.getPort(BSG04AccederBSGPort, BSG04AccederBSG.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BSG04AccederBSG
     */
    @WebEndpoint(name = "BSG04_Acceder_BSGPort")
    public BSG04AccederBSG getBSG04AccederBSGPort(WebServiceFeature... features) {
        return super.getPort(BSG04AccederBSGPort, BSG04AccederBSG.class, features);
    }

}
