package com.example.restapi.bsg.rc.autenticacion;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2020-07-09T13:52:25.351-05:00
 * Generated source version: 3.1.4
 *
 */
@WebService(targetNamespace = "http://bsg.gob.ec/AccesoBSGService", name = "BSG04_Acceder_BSG")
@XmlSeeAlso({ObjectFactory.class})
public interface BSG04AccederBSG {

    @WebMethod(operationName = "ValidarPermiso")
    @RequestWrapper(localName = "ValidarPermiso", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "com.becas.exceluploader.bsg.rc;.autenticacion.ValidarPermiso")
    @ResponseWrapper(localName = "ValidarPermisoResponse", targetNamespace = "http://bsg.gob.ec/AccesoBSGService", className = "com.becas.exceluploader.bsg.rc;.autenticacion.ValidarPermisoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.example.restapi.bsg.rc.autenticacion.ValidarPermisoRespuesta validarPermiso(
        @WebParam(name = "ValidarPermisoPeticion", targetNamespace = "")
        com.example.restapi.bsg.rc.autenticacion.ValidarPermisoPeticion validarPermisoPeticion
    );
}
