
package com.example.restapi.rc;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "InteroperadorlImplService", targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", wsdlLocation = "https://interoperabilidad.dinardap.gob.ec/interoperador?wsdl")
public class InteroperadorlImplService
    extends Service
{

    private final static URL INTEROPERADORLIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.example.restapi.rc.InteroperadorlImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.example.restapi.rc.InteroperadorlImplService.class.getResource(".");
            url = new URL(baseUrl, "https://interoperabilidad.dinardap.gob.ec/interoperador?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'https://interoperabilidad.dinardap.gob.ec/interoperador?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INTEROPERADORLIMPLSERVICE_WSDL_LOCATION = url;
    }

    public InteroperadorlImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InteroperadorlImplService() {
        super(INTEROPERADORLIMPLSERVICE_WSDL_LOCATION, new QName("http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", "InteroperadorlImplService"));
    }

    /**
     *
     * @return
     *     returns InteroperadorlImpl
     */
    @WebEndpoint(name = "InteroperadorlImplPort")
    public InteroperadorlImpl getInteroperadorlImplPort() {
        return super.getPort(new QName("http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", "InteroperadorlImplPort"), InteroperadorlImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InteroperadorlImpl
     */
    @WebEndpoint(name = "InteroperadorlImplPort")
    public InteroperadorlImpl getInteroperadorlImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", "InteroperadorlImplPort"), InteroperadorlImpl.class, features);
    }

}
