
package com.example.restapi.rc;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 *
 */
@WebService(targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", name = "InteroperadorlImpl")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface InteroperadorlImpl {

    @WebResult(name = "getFichaGeneralResponse", targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/", partName = "parameters")
    @WebMethod
    public GetFichaGeneralResponse getFichaGeneral(
        @WebParam(partName = "parameters", name = "getFichaGeneral", targetNamespace = "http://servicio.interoperadorws.interoperacion.dinardap.gob.ec/")
        GetFichaGeneral parameters
    );

    Persona datosTemporalesAspirante(@WebParam(name = "cedula") String cedula, Integer bsg, Integer dinardap, Integer datoSeguro, Long timeoutWS) throws Exception;
}
